#!/bin/bash

newline="----------------------------------------------------------------------------------------------"
newlinefinal="\n\n"
tab="\t"

update(){
    sudo apt-get update -y
    sudo apt-get upgrade -y
}

clean(){
    sudo apt-get clean -y
    sudo apt-get autoclean -y 
    sudo apt-get autoremove -y
    sudo apt-get --purge autoremove -y
}

clean_temp(){
    sudo dpkg --configure -a 
	sudo apt-get install -f -y
	sudo apt-get -f install -y
    sudo rm -rf /home/israelcunha/.local/share/Trash/files/* 
    rm -vfr ~/.thumbnails/normal/* 
	rm -f ~/.cache/thumbnails/normal/* 
    sudo rm -rf /var/cache/snapd 
}

internet_test() {
	ping www.google.com.br -c 1 >/dev/null; 

	if [ "$?" = "0" ] ;
	then
		echo -e "${newlinefinal}" 
		echo -e "${newline}"
	    echo "==> Conexão Estável		";
	    echo -e "${newline}"
	    echo "==> Teste de Conexão - SPEEDTEST	";
		echo -e "${newline}"
		speedtest-cli
		echo -e "${newline}"
	else
		echo -e "${newlinefinal}" 
		echo -e "${newline}"
	    echo "==> Conexão Instável. 	"
	    echo -e "${newline}"
	fi
}


update_extensions(){
    
}





internet_test
update
clean
clean_temp